Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/03/2022
Var
// Seção de Declarações das variáveis 
    A: inteiro
    B: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    A <- Abs(-50)
    Escreval (A)
    B <- RaizQ(81)
    Escreva (B)
    
Fimalgoritmo