Algoritmo "teste"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/03/2022
Var
// Seção de Declarações das variáveis 
    msg: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    msg <- "Ola, Mundo"
    Escreval(msg,", me livrei da maldicao")

    
Fimalgoritmo